# Docker-compose.yml file for atbaker/docker-django project

# Nginx
nginx:
    image: andrecp/test-nginx
    links:
        - django
    ports:
        - "80:80"

# This defines a service for the Django app
django:
    image: andrecp/test-django
    expose:
        - "8000"
    links:
        - postgres


# This defines a service for the Postgres database
postgres:
    image: postgres:9.3


